id: PC891C468
initial_creation_type: ocr
source_metadata:
  volumes:
    208600e58c6a4adc946452c3b35e1cb8:
      base_file: v108.txt
      image_group_id: I1PD95953
      title: རྣམ་དབྱེའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1801
      volume_number: 108
